version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/app
      # - ./src:/app/src
      # - ./package.json:/app/package.json
      # - ./package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=dev
